source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'Climately' do
  pod 'DateTools' # https://github.com/MatthewYork/DateTools
  pod 'Fabric'
  pod 'Crashlytics'
  #pod 'LIVBubbleMenu'
end
